name: Run Addition Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NUMBER1: 5
      NUMBER2: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pytest  # You can skip this if no dependencies are needed

    - name: Run tests
      run: |
        # Run tests if you have a test file, e.g., test_main.py
        pytest test_main.py || echo "No tests found"
      
    - name: Perform Addition
      run: |
        # Get parameters from GitHub Actions environment
        num1=${{ env.NUMBER1 }}
        num2=${{ env.NUMBER2 }}
        
        # Perform addition and output the result
        sum=$((num1 + num2))
        echo "The sum of $num1 and $num2 is: $sum"
